
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftORleftANDnonassocEQUALleftPLUSMINUSleftTIMESDIVIDEleftLPARENRPARENABSOLUTE AND ARRAY ASSIGNMENT BEGIN BOOLEAN_LITERAL CHARACTER_LITERAL COLON COMMA CONST DESTRUCTOR DISTINT DIV DIVIDE DO DOT DOUBLEQUOTE DOWNTO END EQUAL FLOAT FOR FUNCTION GREATER GREATEREQUAL ID IF IN INPUT INTEGER INTERFACE LABEL LBLOCK LBRACKET LESS LESSEQUAL LPAREN MINUS NIL NUMBER OBJECT OR OUTPUT PLUS PRIVATE PROCEDURE PROGRAM QUOTE RBLOCK RBRACKET READ READLN REPEAT RPAREN SEMICOLON SHL STRING STRING_LITERAL THEN TIMES TO UNIT UNTIL USES VAR VIRTUAL WHILE WRITE WRITELN XORprogram : PROGRAM ID SEMICOLON uses_clause_opt block DOTuses_clause_opt : uses_clause\n| emptyunit_list : unit_list COMMA ID\n| IDuses_clause : USES unit_list SEMICOLONblock : declarations compound_statementdeclarations : declaration_list\n| emptydeclaration_list : declaration_list declaration\n| declarationdeclaration : var_declaration\n| const_declarationvar_declaration : VAR var_declaration_listvar_declaration_list : var_declaration_list var_decl\n| var_declvar_decl : id_list COLON ID SEMICOLONid_list : id_list COMMA ID\n| IDconst_declaration : CONST const_listconst_list : const_list const_definition SEMICOLON\n| const_definition SEMICOLONconst_definition : ID EQUAL constantcompound_statement : BEGIN statement_list ENDstatement_list : statement\n| statement_list SEMICOLON statementstatement : simple_statement\n| compound_statementsimple_statement : assignment_statement\n| emptyassignment_statement : ID EQUAL expressionexpression : expression PLUS expression\n| expression MINUS expression\n| expression TIMES expression\n| expression DIVIDE expression\n| LPAREN expression RPAREN\n| ID\n| NUMBERconstant : NUMBER\n| STRING_LITERAL\n| CHARACTER_LITERAL\n| BOOLEAN_LITERALempty :'
    
_lr_action_items = {'PROGRAM':([0,],[2,]),'$end':([1,20,],[0,-1,]),'ID':([2,8,16,17,22,24,25,28,32,40,41,42,44,48,49,52,61,63,64,65,66,67,],[3,19,27,30,39,27,-16,30,46,-15,50,51,-22,39,59,-21,59,-17,59,59,59,59,]),'SEMICOLON':([3,18,19,22,29,33,34,35,36,37,38,43,46,47,48,50,53,54,55,56,57,58,59,60,62,69,70,71,72,73,],[4,31,-5,-43,44,48,-25,-27,-28,-29,-30,52,-4,-24,-43,63,-23,-39,-40,-41,-42,-26,-37,-31,-38,-32,-33,-34,-35,-36,]),'USES':([4,],[8,]),'VAR':([4,5,6,7,11,13,14,15,23,24,25,28,31,40,44,52,63,],[-43,16,-2,-3,16,-11,-12,-13,-10,-14,-16,-20,-6,-15,-22,-21,-17,]),'CONST':([4,5,6,7,11,13,14,15,23,24,25,28,31,40,44,52,63,],[-43,17,-2,-3,17,-11,-12,-13,-10,-14,-16,-20,-6,-15,-22,-21,-17,]),'BEGIN':([4,5,6,7,10,11,12,13,14,15,22,23,24,25,28,31,40,44,48,52,63,],[-43,-43,-2,-3,22,-8,-9,-11,-12,-13,22,-10,-14,-16,-20,-6,-15,-22,22,-21,-17,]),'DOT':([9,21,47,],[20,-7,-24,]),'COMMA':([18,19,26,27,46,51,],[32,-5,42,-19,-4,-18,]),'END':([22,33,34,35,36,37,38,47,48,58,59,60,62,69,70,71,72,73,],[-43,47,-25,-27,-28,-29,-30,-24,-43,-26,-37,-31,-38,-32,-33,-34,-35,-36,]),'COLON':([26,27,51,],[41,-19,-18,]),'EQUAL':([30,39,],[45,49,]),'NUMBER':([45,49,61,64,65,66,67,],[54,62,62,62,62,62,62,]),'STRING_LITERAL':([45,],[55,]),'CHARACTER_LITERAL':([45,],[56,]),'BOOLEAN_LITERAL':([45,],[57,]),'LPAREN':([49,61,64,65,66,67,],[61,61,61,61,61,61,]),'PLUS':([59,60,62,68,69,70,71,72,73,],[-37,64,-38,64,-32,-33,-34,-35,-36,]),'MINUS':([59,60,62,68,69,70,71,72,73,],[-37,65,-38,65,-32,-33,-34,-35,-36,]),'TIMES':([59,60,62,68,69,70,71,72,73,],[-37,66,-38,66,66,66,-34,-35,-36,]),'DIVIDE':([59,60,62,68,69,70,71,72,73,],[-37,67,-38,67,67,67,-34,-35,-36,]),'RPAREN':([59,62,68,69,70,71,72,73,],[-37,-38,73,-32,-33,-34,-35,-36,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'uses_clause_opt':([4,],[5,]),'uses_clause':([4,],[6,]),'empty':([4,5,22,48,],[7,12,38,38,]),'block':([5,],[9,]),'declarations':([5,],[10,]),'declaration_list':([5,],[11,]),'declaration':([5,11,],[13,23,]),'var_declaration':([5,11,],[14,14,]),'const_declaration':([5,11,],[15,15,]),'unit_list':([8,],[18,]),'compound_statement':([10,22,48,],[21,36,36,]),'var_declaration_list':([16,],[24,]),'var_decl':([16,24,],[25,40,]),'id_list':([16,24,],[26,26,]),'const_list':([17,],[28,]),'const_definition':([17,28,],[29,43,]),'statement_list':([22,],[33,]),'statement':([22,48,],[34,58,]),'simple_statement':([22,48,],[35,35,]),'assignment_statement':([22,48,],[37,37,]),'constant':([45,],[53,]),'expression':([49,61,64,65,66,67,],[60,68,69,70,71,72,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> PROGRAM ID SEMICOLON uses_clause_opt block DOT','program',6,'p_program','mini_pascal_parser.py',20),
  ('uses_clause_opt -> uses_clause','uses_clause_opt',1,'p_uses_clause_opt','mini_pascal_parser.py',24),
  ('uses_clause_opt -> empty','uses_clause_opt',1,'p_uses_clause_opt','mini_pascal_parser.py',25),
  ('unit_list -> unit_list COMMA ID','unit_list',3,'p_unit_list','mini_pascal_parser.py',29),
  ('unit_list -> ID','unit_list',1,'p_unit_list','mini_pascal_parser.py',30),
  ('uses_clause -> USES unit_list SEMICOLON','uses_clause',3,'p_uses_clause','mini_pascal_parser.py',34),
  ('block -> declarations compound_statement','block',2,'p_block','mini_pascal_parser.py',38),
  ('declarations -> declaration_list','declarations',1,'p_declarations','mini_pascal_parser.py',42),
  ('declarations -> empty','declarations',1,'p_declarations','mini_pascal_parser.py',43),
  ('declaration_list -> declaration_list declaration','declaration_list',2,'p_declaration_list','mini_pascal_parser.py',47),
  ('declaration_list -> declaration','declaration_list',1,'p_declaration_list','mini_pascal_parser.py',48),
  ('declaration -> var_declaration','declaration',1,'p_declaration','mini_pascal_parser.py',52),
  ('declaration -> const_declaration','declaration',1,'p_declaration','mini_pascal_parser.py',53),
  ('var_declaration -> VAR var_declaration_list','var_declaration',2,'p_var_declaration','mini_pascal_parser.py',57),
  ('var_declaration_list -> var_declaration_list var_decl','var_declaration_list',2,'p_var_declaration_list','mini_pascal_parser.py',61),
  ('var_declaration_list -> var_decl','var_declaration_list',1,'p_var_declaration_list','mini_pascal_parser.py',62),
  ('var_decl -> id_list COLON ID SEMICOLON','var_decl',4,'p_var_decl','mini_pascal_parser.py',66),
  ('id_list -> id_list COMMA ID','id_list',3,'p_id_list','mini_pascal_parser.py',70),
  ('id_list -> ID','id_list',1,'p_id_list','mini_pascal_parser.py',71),
  ('const_declaration -> CONST const_list','const_declaration',2,'p_const_declaration','mini_pascal_parser.py',75),
  ('const_list -> const_list const_definition SEMICOLON','const_list',3,'p_const_list','mini_pascal_parser.py',79),
  ('const_list -> const_definition SEMICOLON','const_list',2,'p_const_list','mini_pascal_parser.py',80),
  ('const_definition -> ID EQUAL constant','const_definition',3,'p_const_definition','mini_pascal_parser.py',84),
  ('compound_statement -> BEGIN statement_list END','compound_statement',3,'p_compound_statement','mini_pascal_parser.py',88),
  ('statement_list -> statement','statement_list',1,'p_statement_list','mini_pascal_parser.py',92),
  ('statement_list -> statement_list SEMICOLON statement','statement_list',3,'p_statement_list','mini_pascal_parser.py',93),
  ('statement -> simple_statement','statement',1,'p_statement','mini_pascal_parser.py',97),
  ('statement -> compound_statement','statement',1,'p_statement','mini_pascal_parser.py',98),
  ('simple_statement -> assignment_statement','simple_statement',1,'p_simple_statement','mini_pascal_parser.py',102),
  ('simple_statement -> empty','simple_statement',1,'p_simple_statement','mini_pascal_parser.py',103),
  ('assignment_statement -> ID EQUAL expression','assignment_statement',3,'p_assignment_statement','mini_pascal_parser.py',107),
  ('expression -> expression PLUS expression','expression',3,'p_expression','mini_pascal_parser.py',111),
  ('expression -> expression MINUS expression','expression',3,'p_expression','mini_pascal_parser.py',112),
  ('expression -> expression TIMES expression','expression',3,'p_expression','mini_pascal_parser.py',113),
  ('expression -> expression DIVIDE expression','expression',3,'p_expression','mini_pascal_parser.py',114),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression','mini_pascal_parser.py',115),
  ('expression -> ID','expression',1,'p_expression','mini_pascal_parser.py',116),
  ('expression -> NUMBER','expression',1,'p_expression','mini_pascal_parser.py',117),
  ('constant -> NUMBER','constant',1,'p_constant','mini_pascal_parser.py',121),
  ('constant -> STRING_LITERAL','constant',1,'p_constant','mini_pascal_parser.py',122),
  ('constant -> CHARACTER_LITERAL','constant',1,'p_constant','mini_pascal_parser.py',123),
  ('constant -> BOOLEAN_LITERAL','constant',1,'p_constant','mini_pascal_parser.py',124),
  ('empty -> <empty>','empty',0,'p_empty','mini_pascal_parser.py',128),
]
